# Compile libraries on each main push
# Nightly packaging project
# [Upload artifacts]
name: Test workflow
on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/15 * * * *'

defaults:
  run:
    shell: cmd
    working-directory: "d:\\work\\VS\\devops-test\\"
  
jobs:
  build:
    runs-on: self-hosted
    if: ${{ !github.event.schedule }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Compiling DevopsTestEditor Libraries
      run: |
        "%UE_ROOT%\Engine\Build\BatchFiles\Build.bat" DevopsTestEditor Win64 Development -project=%cd%\DevopsTest.uproject

  package:
    runs-on: self-hosted
    if: ${{ github.event.schedule }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Pack DevopsTest
      run: |
        "%UE_ROOT%\Engine\Build\BatchFiles\RunUAT.bat" BuildCookRun -project=%cd%\DevopsTest.uproject -noP4 -platform=Win64 -clientconfig=Development -build -cook -stage -pak -archive -archivedirectory="$(Build.StagingDirectory)"
    - name: Compress
      run: |
        7z a -tzip DevopsTestEditor.zip "$(Build.StagingDirectory)"
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: compressed-DevopsTestEditor
        path: DevopsTestEditor.zip
