# Compile libraries on each main push
# Nightly packaging project
# [Upload artifacts]
name: Test workflow
on:
  push:
    branches:
      - main
  schedule:
    - cron: '42 4 * * *'

defaults:
  run:
    shell: cmd
    working-directory: "d:\\work\\VS\\devops-test\\"
  
jobs:
  build:
    runs-on: self-hosted
    if: ${{ !github.event.schedule }}
    steps:
    - name: Compiling DevopsTestEditor Libraries
      run: |
        "%UE_ROOT%\Engine\Build\BatchFiles\Build.bat" DevopsTestEditor Win64 Development -project=%cd%\DevopsTest.uproject

  package:
    runs-on: self-hosted
    if: ${{ github.event.schedule }}
    steps:
    - name: Pack DevopsTest
      run: |
        "%UE_ROOT%\Engine\Build\BatchFiles\RunUAT.bat" BuildCookRun -project=%cd%\DevopsTest.uproject -noP4 -platform=Win64 -clientconfig=Development -build -cook -stage -pak -archive -archivedirectory="$(Build.StagingDirectory)"
    - name: set path
      run: set ART_PATH=%cd%\Saved\StagedBuilds\Windows\
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: compressed-DevopsTestEditor
        path: d:\work\VS\devops-test\Saved\StagedBuilds\Windows\
        compression-level: 9
        overwrite: true
        retention-days: 5
